Sprint 16
DemidenGo/TrackerApp pull request #3
Opened 2023-05-02 17:59 UTC by DemidenGo

Sprint 16 task completed

2023-05-02 19:35 UTC, IBDesignable requested changes

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Onboarding/OnboardingViewController.swift
> +
Мне не очень нравится создание и хранение страничек-вью-контроллеров в свойствах контроллера. Я считаю, что хранением ссылок на них должен заниматься контроллер-контейнер.
В данном случае контейнер - это UIPageViewController, есть еще UINavigationController и UITabBarController – это все контейнеры, которые правильно выделяют и освобождают память под контроллеры, делают это более оптимально и эффективно, чем если бы мы сами реализовывали эту функциональность.

Если ты интересно, то можешь посмотреть на пример реализации работы с UIPageViewController по ссылке [здесь](https://github.com/cjlarsen/Tutorials/tree/master/PageControllerTutorial). Кодстайл там не идеальный, но концепция понятна и реализована в правильном направлении.

Во-первых, в этом примере пейдж-вью-контроллер создается как дочерний контроллер и располагается на кастомном контроллере, который работает с моделью отображаемых страниц (он же является делегатом и датасорсом).

Во-вторых, контроллеры для страниц создаются только в момент их показа. Это означает, что в памяти находится только один отображаемый экран, а не оба сразу.

В-третьих, пример реализации хорошо масштабируемый благодаря тому, что каждой странице соответствует свой вью-контроллер и своя модель данных. Это особенно важно, если у нас большое количество страниц, онбординги в продакшене самая важная часть(по манетизации, и сбору данных)  в могут содержать десятки экранов-страниц. Если мы их стали перечислять тут свойствами, мы бы замучались такой код поддерживать. В проде – создание отдельного контроллера для каждой страницы упрощает организацию кода. Кроме того, если на каждом вью-контроллере отображаются тяжелые ресурсы, такие как изображения или видео, хранение всего сразу в памяти может не только тротлить у пользователя, но и система может выгрузить нас – будет выглядеть как краш.  

Возвращаясь к нашей задаче, я заметила, то ты хорошо выделил повторяющиеся элементы интерфейса, такие как изображение и заголовок (оформлены в виде функций (makeImageView, makeLabel).  Если присмотреться, то можно заметить, что наши две пейджи на самом деле имеют одинаковую верстку и отличаются только данными. Поэтому правильным решением было бы создать отдельный контроллер OnboardingPageViewController, который инициализируется данными модели (например, изображением и текстом, или можно кейс enum, как в примере выше). 

После этого останется только модернизировать логику навигации вперед-назад.

Текущее решение надо переписать, я не приму его в таком виде.

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Onboarding/OnboardingViewController.swift
> +    }
в обоих случаях можно испрользовать тернарный оператор

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Onboarding/OnboardingViewController.swift
> +    private lazy var button: UIButton = {
понятно, что кнопка, но лучше все-таки передавать смысл кнопки, используй формулу "Назначение"+тип элемента, loginButton/nextButton/closeButton

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Onboarding/OnboardingViewController.swift
> +    private lazy var pages = [firstViewController, secondViewController]
следую комментарию выше, здесь должен получиться не массив контроллеров, а массив данных – кейсы енапов, или других структур, какие посчитаешь нужным.

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Onboarding/OnboardingViewController.swift
> +    @objc private func buttonAction() {
опять же, не очень понятное название, что дальше произойдет - не известно. FinishOnboarding/CloseOnboarding.

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Onboarding/OnboardingViewController.swift
> +        setupConstraints(in: secondViewController, for: [secondImageView, secondLabel])
вот здесь хорошо заметно, как дублируется код, вместо того чтобы иметь по одной лейбле и картинке внутри контроллера, храним сразу две. Причем ссылки держать будет как контейнер (OnboardingViewController), так и пейджи, в качестве вьюх в их иерархии. Скапливается мусор.

Нужно научиться это подмечать и писать более переиспользуемый код – такое ценится у разработчиков

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Onboarding/OnboardingViewController.swift
> +              let label = views.first(where: { $0 is UILabel }) else { return }
Еще один пример странноватого кода, который можно было бы избежать, если не поленишься описать отдельный вью-контроллер

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/SceneDelegate.swift
> +        }
`UserDefaults.standard.hasLaunchBefore = true` – в данном случае прототипируется логика, в которой после первого запуска онбординг больше не покажется, в данном типе онбординга это ок. Но если присмотреться к приложениям в сторе, то чаще всего онбординг перестает показываться после активного действия пользователя (завершения онбординга или его пропуск).

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
> +    lazy var newCategoryViewController = NewCategoryViewController()
Еще раз повторюсь: вью-контроллеры создаются только в момент перехода. 
Лишних действий делать не нужно, даже если это lazy свойство – это не правильно.

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
> +    var viewModel: CategoriesViewModelProtocol?
хорошо что модель закрыта протоколом

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/Model/CategoryStoreProtocol.swift
> +}
В слое данных не должно быть зависимостей от фреймворков пользовательского интерфейса, как UIKit.  Нужно будет переписать интерфейсы таким образом, чтобы можно было обойтись без импорта UIKit.

Важно изолировать слои данных, чтобы их можно было переиспользовать на разных платформах и в разных проектах. Такой код может быть удобно выделен в платформо-независимые пакеты, которые можно использовать как библиотеки. Важно этот навык отрабатывать и держать в голове, это ценно. 

В macOS или в watchOS нам недоступен UIKit, и в этом случае, нам бы пришлось писать дополнительные реализации одной и той же функциональности

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
> +    }
Здесь очень хорошо, что инициализация сделана с параметром от вью модели, правда не очень понятно зачем она передана по явному типу, ведь по идее нам достаточно только протокольного типа – это нужно исправить. 

И почему метод называется initialize, есть же init :) давай использовать стандартный инит, а не мимикрировать под него.

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
>      }
баиндинг надо сделать во viewDidLoad – это получится сделать, если вью контроллер будет проинициализирован от вью модели

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
>              }
почему бы эту логику не отдать вью моделе? По идее слой View должен быть максимально "тупым" – пришла какая-то категория. 
View: ViewModel - забери, обработай, не знаю что делать с ней.
ViewModel – сверилась c Model, опредилала что делать, записала даные в Model, вернула через байндинги что делать/показывать View. 

вот эта логика здесь лишняя, ее нужно сместить в сторону ViewModel

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
> +            self.categoriesTableView.scrollToRow(at: indexPathToScroll, at: .bottom, animated: false)
Вот эта логика должна быть закрыта байндингом, на сколько я поняла ход твоих мыслей.

Положил категорию – вью модель вернула индекс, вью - поскролила от нового индекса.

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/ViewModel/CategoriesViewModel.swift
> +    private(set) var categories: [CategoryViewModel] = []
вот тут круто, что у ячеек свои вьюмодели - молодец!

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/ViewModel/CategoriesViewModel.swift
> +    }
Дополню комментарий относительно тупости Вьюхи, здесь ViewModel выступает сильно простенькой прослоечкой к данным. Давай ей дадим ответственность содержать бизнес-логику экрана

2023-05-02 19:35 UTC, IBDesignable commented on TrackerApp/Trackers/TrackerCreationViewController.swift
> +        categoriesViewController.initialize(CategoriesViewModel())
Здесь похоже тоже categoriesViewController - хранится во вью-контроллере. 

Мне кажется, или я не только в этом спринте говорила, что от этого подхода надо избавиться?

2023-05-02 19:39 UTC, IBDesignable commented
Коротко, вроде усвоены принципы в MVVM – протоколы, байдинги. 

Не очень хорошо уложились знания про разделение слоев, в работе смешиваваются слои, сборка модуля происходит не через инициализатор – это неверная реализация архитектуры, придется еще раз плотно подойти к работе. Юрий, не стесняйся спрашивать Наставников или Наставниц. 

Архитектурные приемы не самая тривиальная штука, их надо переживывать, смотреть чужой код чтобы тренировать насмотренность. 

В данной работе накопилось много техдолга в виде лейзи-контроллеров – это плохопахнущий код, который к сожалению, прошел предыдущие ревью. Его нужно исправить, чтобы я смогла принять работу.

2023-05-04 09:50 UTC, IBDesignable requested changes

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageViewModel.swift
> +    static var loginButtonTapAction: (() -> Void)?
хранимые свойства у енамов не нужно делать, это нарушает смысл этого типа данных, тем более статику, которую можно вообще из любого места переопределить. 

 Давай его отсюда уберем, и передадим явно в инициализатор PageView, либо же сделаем это через делегирование.

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/SceneDelegate.swift
> +            let pageViewController = UIPageViewController(transitionStyle: .scroll,
давай это инкапсулируем в onboardingViewController, нет необходимости создавать контроллер во вне.

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/Model/CategoryStoreProtocol.swift
> +import Foundation
в прошлый раз что-то я перемудрила, забыла что IndexPath уже давно живет в Foundation)

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
> +    var newCategoryViewController: NewCategoryViewController?
Я в прошлый раз писала, что нужно избавиться от этого свойства совсем.

Расскажи, в чем мотивация сохранять контроллеры? какой ты профит в этом находишь? 

Я все еще настаиваю, что это не нужно делать без особой причины, ссылку на вьюконтролеры система сама хранит за счет навигационных контейнеров и window. Твой способ заставляет жить вью-контроллер, даже если он не отображается в иерархии, то есть задействовать лишние ресурсы, к тому же требует от разработчика работающего с данным способом дополнительно следить за состоянием содержимого вью-контроллера. Это плохая практика, в проде за такое бьют по рукам) 

Поэтому хочу понять в чем смысл, поясни)

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
> +        guard let newCategoryViewController = newCategoryViewController else { return }
можно же проще:

```suggestion
        let newCategoryViewController = NewCategoryViewController()
```

Это все еще относится к моему комментарию про сохранение ссылок)

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/ViewModel/CategoriesViewModel.swift
> +        selectCategory(at: indexPath)
круто что появились приватные методы

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageModel.swift
> +final class PageModel: UIViewController {
я сначала подумала что это ViewModel по названию, потом увидела наследование. 

Давай придерживаться общепринятых неймингов. Если у тебя элемент типа UIView – хорошо бы в названии это отразить, если элемент относится к UIViewController, значит и нейминг должен содержать ViewController. Ну и название должно отображать суть модуля(экрана). В данном случае это все еще онбординговый экран – то есть OnboardingViewController

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageModel.swift
> +    }
Давай UIPageViewController создавать прямо в setupPageController, тогда и от инита избавимся, и от лишнего поля (pageController: UIPageViewController?), ты же его больше не используешь нигде.

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageModel.swift
> +final class PageModel: UIViewController {
Вот у [Dodo статья в общем смысле про нейминг](https://habr.com/ru/companies/dododev/articles/714512/ ), не только про ios-разработку.

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageModel.swift
> +    }
как уже выше писала, переопредялять статику таким образом не стоит, это плохой паттерн, потому что я могу это сделать вообще откуда угодно и ничто мне не помешает это сделать. 

вполне ок, оставить здесь просто содержимое кложуры 
```suggestion
    private func setupFinishOnboarding() {
        guard let window = UIApplication.shared.windows.first else {
                fatalError("Invalid Configuration: unable to get window from UIApplication")
        }
        let tabBarController = TabBarController()
        window.rootViewController = tabBarController
        window.makeKeyAndVisible()
    }
```

и передать ее в инициализатор вью: 
```
PageView(with: pages[previousPageIndex], action: setupFinishOnboarding) 
``` 
здесь вместо кложуры { [weak self] in ... } сразу передаем ссылку на функцию `setupFinishOnboarding` (потребует указания сбегающего замыкания в инициализаторе @escaping)

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageView.swift
> +final class PageView: UIViewController {
Надо добавить к имени ViewController

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageViewModel.swift
> +//  PageModel.swift
Файл назвается не Pages и комментарий не соответсвтует содержимому, давай поправим

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageViewModel.swift
> +enum Pages: CaseIterable {
Pages очень обширное название, в приложении можно разные страницы встретить, от онбординга, до страниц историй например, или пагинации данных. Поэтому лучше переназвать как-нибудь связано с онбордингом, например OnboardingPage.

Ну енамы принято называть в единственном числе, потому что ты обращаешься всегда к какому-то одному из кейсов

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageModel.swift
> +//  OnboardingViewController.swift
имя файла и комментарии опять расходятся, проверь здесь и в других местах тоже

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageModel.swift
> +        let previousPageIndex = currentPageIndex - 1
Можно лучше! добавить в енам Pages логику получения нового индекса вперед/назад: 

```swift 
var next: Pages? {
  switch self {
  case first: return .second 
  case .second: return nil 
  } 
}

var previous: Pages? {
// аналогично 
}
```

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageModel.swift
> +        }
не очень тривиально на самом деле это читается. Но если я правильно поняла, то эта логика позволяет каруселькой перемещаться между страницами. 

Если воспользоваться советом выше про next/previous, только убрать опциональность,  то логика упростится:
```swift
return PageView(with: currentPage.page.previous)
```

заодно от массива pages можно будет избавиться.

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Trackers/TrackerCreationViewController.swift
> +    var scheduleViewController: ScheduleViewController?
Надо будет убрать здесь и далее по коду ссылки на вью-контроллеры. Убираем прямо целиком эти свойства.

2023-05-04 09:50 UTC, IBDesignable commented on TrackerApp/Onboarding/PageModel.swift
> +        pageController.didMove(toParent: self)
Можно не инициализировать текущий вью-контроллер от UIPageViewController, и создавать его прямо здесь.

2023-05-04 14:10 UTC, DemidenGo commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
> +    var newCategoryViewController: NewCategoryViewController?
Добрый день! Делал так, чтобы получить менее связанный код и лучше тестируемый в дальнейшем. По крайней мере, мне так казалось) То есть, грубо говоря, хотел иметь возможность подменить реализацию следующего контроллера через доступ к свойству текущего контроллера.

2023-05-04 19:26 UTC, IBDesignable commented on TrackerApp/Trackers/Categories-MVVM/View/CategoriesViewController.swift
> +    var newCategoryViewController: NewCategoryViewController?
о как) ну это тебе вряд ли поможет) во первых, почти во всех случаях переменные были явного типа – то есть ну хотя бы протоколом тогда закрывать. И код наоборот как раз получается связанным, раз зависит от конкретных реализаций.
Во-вторых, принципы [dry/kiss/yagni](https://habr.com/ru/companies/itelma/articles/546372/) должны тебя уберегать от того, что не нужно делать то, что тебе не нужно :)

ну и обычно переходы между контроллерами не мокаются, достаточно UI-теста сквозного по самому позитивному и длинному сценарию.

2023-05-04 19:29 UTC, IBDesignable approved these changes
Здорово! Можно двигаться дальше)

2023-05-04 19:29 UTC, IBDesignable commented on TrackerApp/Onboarding/OnboardingPage.swift
> +    }
какова красота)

2023-05-04 19:29 UTC, IBDesignable commented on TrackerApp/Onboarding/OnboardingViewController.swift
> +//MARK: - UIPageViewControllerDataSource
кажется теперь даже кода стало меньше, и почище выглядит :)

2023-05-05 12:51 UTC, merged